#define LANGUAGE_DE
//#define LANGUAGE_EN

#ifdef LANGUAGE_EN

#define TEXT_BROWSE_SONG_PLAY "Play"
#define TEXT_BROWSE_SONG_ADDTOQUEUE "Add to queue"
#define TEXT_BROWSE_SONG_CLEARANDPLAY "Clear and play"
#define TEXT_BROWSE_SONG_ADDTOPLAYLIST "Add to Playlist"
#define TEXT_BROWSE_SONG_ADDTOFAVORITES "Add to Favorites"

#define TEXT_BROWSE_WEBRADIO_PLAY "Play"
#define TEXT_BROWSE_WEBRADIO_ADDTOQUEUE "Add to queue"
#define TEXT_BROWSE_WEBRADIO_CLEARANDPLAY "Clear and play"
#define TEXT_BROWSE_WEBRADIO_ADDTOPLAYLIST "Add to Playlist"
#define TEXT_BROWSE_WEBRADIO_ADDTOFAVORITES "Add to Favorites"

#define TEXT_BROWSE_FOLDER_PLAY "Play"
#define TEXT_BROWSE_FOLDER_ADDTOQUEUE "Add to queue"
#define TEXT_BROWSE_FOLDER_CLEARANDPLAY "Clear and play"

#define TEXT_QUEUE_TRACK_PLAY "Play"
#define TEXT_QUEUE_TRACK_DELETE "Delete"

#define TEXT_HOME "Home"
#define TEXT_BACK "Back"
#define TEXT_CLEAR "Clear"

#define TEXT_MENU_STATUS "Status"
#define TEXT_MENU_BROWSE "Browse"
#define TEXT_MENU_PLAYBACK "Playback"
#define TEXT_MENU_QUEUE "Queue"
#define TEXT_MENU_DARK "Display off"

#define TEXT_PLAYBACK_PREV "Prev"
#define TEXT_PLAYBACK_NEXT "Next"
#define TEXT_PLAYBACK_PLAY "Play"
#define TEXT_PLAYBACK_PAUSE "Pause"
#define TEXT_PLAYBACK_TOGGLE "Toggle"
#define TEXT_PLAYBACK_STOP "Stop"
#define TEXT_PLAYBACK_RANDOM "Random"
#define TEXT_PLAYBACK_REPEAT "Repeat"

#define TEXT_WL_CONNECTED "WL_CONNECTED"
#define TEXT_WL_NO_SHIELD "WL_NO_SHIELD"
#define TEXT_WL_IDLE_STATUS "WL_IDLE_STATUS"
#define TEXT_WL_NO_SSID_AVAIL "WL_NO_SSID_AVAIL"
#define TEXT_WL_SCAN_COMPLETED "WL_SCAN_COMPLETED"
#define TEXT_WL_CONNECT_FAILED "WL_CONNECT_FAILED"
#define TEXT_WL_CONNECTION_LOST "WL_CONNECTION_LOST"
#define TEXT_WL_DISCONNECTED "WL_DISCONNECTED"

#endif

#ifdef LANGUAGE_DE

#define TEXT_BROWSE_SONG_PLAY "Wiedergeben"
#define TEXT_BROWSE_SONG_ADDTOQUEUE "Zur Warteschlange"
#define TEXT_BROWSE_SONG_CLEARANDPLAY "Warteschlange ersetzen"
#define TEXT_BROWSE_SONG_ADDTOPLAYLIST "zur Playlist"
#define TEXT_BROWSE_SONG_ADDTOFAVORITES "zu Favoriten"

#define TEXT_BROWSE_WEBRADIO_PLAY "Wiedergeben"
#define TEXT_BROWSE_WEBRADIO_ADDTOQUEUE "Zur Warteschlange"
#define TEXT_BROWSE_WEBRADIO_CLEARANDPLAY "Warteschlange ersetzen"
#define TEXT_BROWSE_WEBRADIO_ADDTOPLAYLIST "zur Playlist"
#define TEXT_BROWSE_WEBRADIO_ADDTOFAVORITES "zu Favoriten"

#define TEXT_BROWSE_FOLDER_PLAY "Wiedergeben"
#define TEXT_BROWSE_FOLDER_ADDTOQUEUE "Zur Warteschlange"
#define TEXT_BROWSE_FOLDER_CLEARANDPLAY "Warteschlange ersetzen"

#define TEXT_QUEUE_TRACK_PLAY "Wiedergeben"
#define TEXT_QUEUE_TRACK_DELETE "Löschen"

#define TEXT_HOME "Hauptmenü"
#define TEXT_BACK "Zurück"
#define TEXT_CLEAR "Löschen"

#define TEXT_MENU_STATUS "Status"
#define TEXT_MENU_BROWSE "Durchsuchen"
#define TEXT_MENU_PLAYBACK "Steuerung"
#define TEXT_MENU_QUEUE "Warteschlange"
#define TEXT_MENU_DARK "Display aus"

#define TEXT_PLAYBACK_PREV "Vorheriger Titel"
#define TEXT_PLAYBACK_NEXT "Nächster Titel"
#define TEXT_PLAYBACK_PLAY "Play"
#define TEXT_PLAYBACK_PAUSE "Pause"
#define TEXT_PLAYBACK_TOGGLE "Play/Pause"
#define TEXT_PLAYBACK_STOP "Stop"
#define TEXT_PLAYBACK_RANDOM "Zufällig"
#define TEXT_PLAYBACK_REPEAT "Wiederholen"


#define TEXT_WL_CONNECTED "WL_CONNECTED"
#define TEXT_WL_NO_SHIELD "WL_NO_SHIELD"
#define TEXT_WL_IDLE_STATUS "WL_IDLE_STATUS"
#define TEXT_WL_NO_SSID_AVAIL "WL_NO_SSID_AVAIL"
#define TEXT_WL_SCAN_COMPLETED "WL_SCAN_COMPLETED"
#define TEXT_WL_CONNECT_FAILED "WL_CONNECT_FAILED"
#define TEXT_WL_CONNECTION_LOST "WL_CONNECTION_LOST"
#define TEXT_WL_DISCONNECTED "WL_DISCONNECTED"

#define TEXT_CONNECT_WLAN "Verbinde mit WLAN"
#define TEXT_CONNECT_VOLUMIO "Verbinde mit Volumio"



#endif